import {playerOverview} from '@/lib/football/players';
import {diagnostics} from '@/lib/football/diagnostics';
import {canManage,validWrite} from '@/lib/football/settings-policy';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database,setting,lock} from '@/lib/football/store';
import {secretNames,secret} from '@/lib/football/secrets';
import {seal} from '@/lib/football/crypto';
import {collectOdds,collectPlayers} from '@/lib/football/providers';
export const dynamic='force-dynamic';
const reply=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
async function authorized(){const user=await getChatGPTUser();return canManage(user,setting('ADMIN_EMAIL'))}
export async function GET(){if(!await authorized())return reply({error:'Connexion au compte propriétaire requise.'},403);try{return reply({configured:Object.fromEntries(await Promise.all(secretNames.map(async name=>[name,!!await secret(name)]))),ready:!!setting('CREDENTIALS_MASTER_KEY'),diagnostics:await diagnostics()})}catch{return reply({error:'Configuration indisponible.'},503)}}
export async function POST(request:Request){if(!await authorized())return reply({error:'Accès réservé au propriétaire.'},403);if(!validWrite(request.headers.get('origin'),setting('SITE_ORIGIN'),request.headers.get('content-type')))return reply({error:'Origine refusée.'},403);try{const reader=request.body?.getReader();if(!reader)return reply({error:'Requête vide.'},400);let body='',size=0;const decoder=new TextDecoder();for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>4096){await reader.cancel();return reply({error:'Requête trop volumineuse.'},413)}body+=decoder.decode(value,{stream:true})}const input=JSON.parse(body);if(input.action==='collect'){const provider=input.provider==='players'?'players':'odds';if(!await lock('settings:collect:'+provider,60000))return reply({error:'Vérification déjà demandée. Réessayez dans une minute ; les données en cache restent accessibles.'},429);if(provider==='players'){const d=await playerOverview();await database().prepare("DELETE FROM cache WHERE key LIKE 'view:%'").run();return reply({message:`${d.players.length} joueurs disponibles pour la saison ${d.season}.`,players:d.coverage.map(c=>({league:c.league,error:c.count?null:c.status}))})}const odds=await collectOdds();await database().prepare("DELETE FROM cache WHERE key LIKE 'view:%'").run();return reply({message:'Cotes vérifiées. L’écran des matchs a été actualisé.',odds})}if(input.name==='PLAYER_SEASON'&&!/^20[0-9]{2}$/.test(input.value))return reply({error:'Saison invalide.'},400);if(!secretNames.includes(input.name)||typeof input.value!=='string'||input.value.length>512||/[\r\n\x00]/.test(input.value))return reply({error:'Clé invalide.'},400);if(!setting('CREDENTIALS_MASTER_KEY'))return reply({error:'Stockage sécurisé indisponible.'},503);if(!await lock('settings:save',1000))return reply({error:'Réessayez dans une seconde.'},429);const value=input.value.trim();if(value)await database().prepare('INSERT INTO credentials(name,ciphertext,updated_at) VALUES(?,?,?) ON CONFLICT(name) DO UPDATE SET ciphertext=excluded.ciphertext,updated_at=excluded.updated_at').bind(input.name,await seal(value,setting('CREDENTIALS_MASTER_KEY'),input.name),new Date().toISOString()).run();else await database().prepare('DELETE FROM credentials WHERE name=?').bind(input.name).run();if(['API_FOOTBALL_KEY','PLAYER_SEASON'].includes(input.name))await database().prepare("UPDATE cache SET expires_at=0 WHERE (key LIKE 'players:%' OR key LIKE 'scorers:%') AND error IS NOT NULL").run();await database().prepare("DELETE FROM cache WHERE key LIKE 'view:%'").run();return reply({message:value?'Clé enregistrée côté serveur.':'Clé supprimée.'})}catch{return reply({error:'Enregistrement ou collecte impossible. Réessayez plus tard.'},503)}}
