import {loadJournal} from '@/lib/football/journal';
import {leagueContext} from '@/lib/football/league-context';
import {decide,decidePrudent,paperReport} from '@/lib/football/decision';
import {compactQuotes,summaryHistory} from '@/lib/football/compact';
import {saveProspective} from '@/lib/football/prospective';
import {prospectiveMetrics} from '@/lib/football/presentation';
import {waitUntil} from 'cloudflare:workers';
import {responseCache} from '@/lib/football/response-cache';
import {fitRolling,matchAnalysis} from '@/lib/football/analysis';
import {LEAGUES,seasonFor} from '@/lib/football/core';
import {readCache} from '@/lib/football/store';
import {secret} from '@/lib/football/secrets';
import {parisDate,validDate,fit,form,walkForward,type Match} from '@/lib/football/core';
import {loadMatches,quotesFor,unmatchedOdds,collectOdds} from '@/lib/football/providers';
import {database,setting} from '@/lib/football/store';
async function build(request:Request){const url=new URL(request.url),day=url.searchParams.get('date')||parisDate();if(!validDate(day)||day<'2025-07-01'||day>'2027-06-30')return Response.json({error:'Date hors couverture : juillet 2025 à juin 2027'},{status:400});try{
 const {matches,coverage}=await loadMatches(day);if(day===parisDate())waitUntil(collectOdds(false,matches).catch(()=>undefined));let quotes:any[]=[],players:any[]=[],history:any[]=[],budgets:any[]=[];let dbError=null;try{[quotes,players]=await Promise.all([quotesFor(matches),Promise.resolve([])]);history=(await database().prepare("SELECT * FROM predictions WHERE version NOT LIKE 'paper-%' ORDER BY published_at DESC LIMIT 100").all()).results;budgets=(await database().prepare('SELECT * FROM budget WHERE key LIKE ? OR key LIKE ?').bind('%'+new Date().toISOString().slice(0,10)+'%','%'+new Date().toISOString().slice(0,7)).all()).results;}catch{dbError='Stockage persistant temporairement indisponible'}
 const selected=matches.filter(m=>m.date===day);const training=[...matches];const previous=String(Number(seasonFor(day).slice(0,4))-1);for(const l of LEAGUES){const r=await readCache(`fd:${previous}-${String(Number(previous)+1).slice(-2)}:${l.fd}`);if(Array.isArray(r?.data?.matches))for(const x of r.data.matches){if(x.status!=='FINISHED'||x.score?.duration!=='REGULAR')continue;training.push({id:`fd:${x.id}`,league:l.id,season:`${previous}-${String(Number(previous)+1).slice(-2)}`,date:parisDate(x.utcDate),utc:x.utcDate,home:x.homeTeam.name,away:x.awayTeam.name,homeId:`fd:${x.homeTeam.id}`,awayId:`fd:${x.awayTeam.id}`,hg:x.score.fullTime.home,ag:x.score.fullTime.away,status:x.status,source:'football-data.org',collectedAt:r.collected_at,round:null})}}const detailId=url.searchParams.get('match');const m=matches.find(x=>x.id===detailId);const detail=m?{match:m,leagueContext:leagueContext(matches,m),model:fitRolling(training,m),forms:[5,10].map(n=>({n,home:form(training,m.homeId,m.date,n),away:form(training,m.awayId,m.date,n),homeVenue:form(training,m.homeId,m.date,n,'home'),awayVenue:form(training,m.awayId,m.date,n,'away')})),h2h:matches.filter(x=>x.status==='FINISHED'&&x.date<m.date&&((x.homeId===m.homeId&&x.awayId===m.awayId)||(x.homeId===m.awayId&&x.awayId===m.homeId))).slice(-5),quotes:quotes.filter(q=>q.matchId===m.id)}:null;
 const analyses=selected.map(m=>{const a=matchAnalysis(training,m,quotes);return {...a,decision:decidePrudent(a),baselineDecision:decide(a)}});if(day===parisDate()){try{await saveProspective(analyses,matches,quotes);history=(await database().prepare("SELECT * FROM predictions WHERE version NOT LIKE 'paper-%' ORDER BY published_at DESC LIMIT 100").all()).results}catch{dbError='Historique des analyses temporairement indisponible'}}
 const next=matches.filter(m=>m.date>day).map(m=>m.date).sort()[0]??null;
 const extended=url.searchParams.get('view')==='analysis';let paper=null;if(extended){try{paper=await loadJournal()}catch{dbError='Journal simulé temporairement indisponible'}}return Response.json({date:day,matches:detailId?[]:selected,coverage,unmatchedOdds:detailId?[]:(await unmatchedOdds(day)).map(e=>({...e,quotes:e.quotes.filter((q:any)=>['Draw',e.home,e.away].includes(q.outcome)).sort((a:any,b:any)=>b.price-a.price).filter((q:any,i:number,all:any[])=>all.findIndex((x:any)=>x.outcome===q.outcome)===i)})),analyses:extended?analyses:[],paper,prospective:extended?prospectiveMetrics(history):null,quotes:detailId?[]:compactQuotes(quotes.filter(q=>selected.some(m=>m.id===q.matchId))),players:[],detail,next,history:extended?summaryHistory(history):[],budgets,dbError,configured:{calendar:!!(await secret('FOOTBALL_DATA_KEY')),odds:!!(await secret('ODDS_API_KEY')),players:!!(await secret('API_FOOTBALL_KEY'))},validation:url.searchParams.get('validation')==='1'?coverage.map(c=>({league:c.name,...walkForward(matches.filter(m=>m.league===c.id),fitRolling)})):null},{headers:{'Cache-Control':'private, max-age=30'}});
 }catch{return Response.json({error:'Chargement impossible. Réessayez ; aucune donnée de remplacement inventée.'},{status:503})}}

export async function GET(request:Request){const url=new URL(request.url),day=url.searchParams.get('date')||parisDate(),match=url.searchParams.get('match'),validation=url.searchParams.get('validation')==='1';if(!validDate(day)||day<'2025-07-01'||day>'2027-06-30'||(match&&match.length>250))return Response.json({error:'Date ou match hors couverture'},{status:400});const key='view:v12:'+day+(match?':match:'+match:'')+(validation?':validation':'')+(url.searchParams.get('view')==='analysis'?':analysis':'');return responseCache(key,()=>build(request),validation?86400000:300000)}
