import {secret} from '@/lib/football/secrets';
import {parisDate,validDate,fit,form,walkForward,type Match} from '@/lib/football/core';
import {loadMatches,quotesFor,loadPlayers} from '@/lib/football/providers';
import {database,setting} from '@/lib/football/store';
export async function GET(request:Request){const url=new URL(request.url),day=url.searchParams.get('date')||parisDate();if(!validDate(day)||day<'2025-07-01'||day>'2027-06-30')return Response.json({error:'Date hors couverture : juillet 2025 à juin 2027'},{status:400});try{
 const {matches,coverage}=await loadMatches(day);let quotes:any[]=[],players:any[]=[],history:any[]=[],budgets:any[]=[];let dbError=null;try{[quotes,players]=await Promise.all([quotesFor(matches),loadPlayers()]);history=(await database().prepare('SELECT * FROM predictions ORDER BY published_at DESC LIMIT 100').all()).results;budgets=(await database().prepare('SELECT * FROM budget WHERE key LIKE ? OR key LIKE ?').bind('%'+new Date().toISOString().slice(0,10)+'%','%'+new Date().toISOString().slice(0,7)).all()).results;}catch{dbError='Stockage persistant temporairement indisponible'}
 const selected=matches.filter(m=>m.date===day);const detailId=url.searchParams.get('match');const m=matches.find(x=>x.id===detailId);const detail=m?{match:m,model:fit(matches,m),forms:[5,10].map(n=>({n,home:form(matches,m.homeId,m.date,n),away:form(matches,m.awayId,m.date,n),homeVenue:form(matches,m.homeId,m.date,n,'home'),awayVenue:form(matches,m.awayId,m.date,n,'away')})),h2h:matches.filter(x=>x.status==='FINISHED'&&x.date<m.date&&((x.homeId===m.homeId&&x.awayId===m.awayId)||(x.homeId===m.awayId&&x.awayId===m.homeId))).slice(-5),quotes:quotes.filter(q=>q.matchId===m.id)}:null;
 const next=matches.filter(m=>m.date>day).map(m=>m.date).sort()[0]??null;
 return Response.json({date:day,matches:selected,coverage,quotes:quotes.filter(q=>selected.some(m=>m.id===q.matchId)),players,detail,next,history,budgets,dbError,configured:{calendar:!!(await secret('FOOTBALL_DATA_KEY')),odds:!!(await secret('ODDS_API_KEY')),players:!!(await secret('API_FOOTBALL_KEY'))},validation:url.searchParams.get('validation')==='1'?coverage.map(c=>({league:c.name,...walkForward(matches.filter(m=>m.league===c.id))})):null},{headers:{'Cache-Control':'private, max-age=30'}});
 }catch{return Response.json({error:'Chargement impossible. Réessayez ; aucune donnée de remplacement inventée.'},{status:503})}}
