import {cached,readCache,reserve,setting} from './store';
import {secret} from './secrets';
import {LEAGUES,seasonFor,parisDate} from './core';
import {boundedBudget} from './config';
import {playerError} from './matching';
import {loadPlayers} from './providers';
async function request(url:string,headers:Record<string,string>){let r:Response;try{r=await fetch(url,{headers,signal:AbortSignal.timeout(12000)})}catch{throw Error('Fournisseur injoignable ; dernière copie conservée.')}if(!r.ok)throw Error(r.status===429?'Quota fournisseur atteint.':r.status===403||r.status===401?'Clé ou accès à cette fonctionnalité refusé par le fournisseur.':`Fournisseur indisponible (${r.status}).`);return r.json() as Promise<any>}
export async function playerOverview(){const season=Number(await secret('PLAYER_SEASON')||seasonFor(parisDate()).slice(0,4));const existing=await loadPlayers();const players:any[]=[];const coverage:any[]=[];const fd=await secret('FOOTBALL_DATA_KEY'),apif=await secret('API_FOOTBALL_KEY'),rights=await secret('API_FOOTBALL_RIGHTS_CONFIRMED');for(const l of LEAGUES){const full=existing.filter(p=>p.league===l.id);if(full.length){players.push(...full);coverage.push({league:l.name,status:'Statistiques saisonnières API-Football',count:full.length,season});continue}
 // A compact top-scorer list avoids fetching dozens of pages per league.
 let r:any=null;if(fd){r=await cached(`scorers:fd:${l.id}:${season}`,86400000,async()=>{const day=new Date().toISOString().slice(0,10);if(!await reserve('fd:minute:'+new Date().toISOString().slice(0,16),1,8)||!await reserve('fd:day:'+day,1,boundedBudget(setting('CALENDAR_DAILY_BUDGET'),80,80)))throw Error('Budget football-data.org atteint ; réessayez à la minute suivante.');const d=await request(`https://api.football-data.org/v4/competitions/${l.fd}/scorers?season=${season}&limit=20`,{'X-Auth-Token':fd});if(!Array.isArray(d.scorers))throw Error('Liste des buteurs non fournie.');return d.scorers});if(Array.isArray(r.data)&&r.data.length){for(const row of r.data){players.push({id:`fd:player:${row.player.id}:${row.team.id}:${season}`,name:row.player.name,team:row.team.name,league:l.id,season,appearances:row.playedMatches??null,starts:null,minutes:null,goals:row.goals??null,assists:row.assists??null,shots:null,onTarget:null,penaltyGoals:row.penalties??null,goals90:null,assists90:null,xg:null,xa:null,recent:null,source:'football-data.org',scope:'Top 20 buteurs ; passes des joueurs de cette liste, pas classement complet des passeurs',collectedAt:r.collectedAt,stale:r.stale});}coverage.push({league:l.name,season,count:r.data.length,status:r.error||'Top buteurs disponible',source:'football-data.org'});continue}}
 const fdError=r?.error; if(apif&&rights==='true'){r=await cached(`scorers:apif:${l.id}:${season}`,86400000,async()=>{if(!await reserve('apif:'+new Date().toISOString().slice(0,10),1,boundedBudget(setting('PLAYERS_DAILY_BUDGET'),80,80)))throw Error('Budget API-Football atteint.');const d=await request(`https://v3.football.api-sports.io/players/topscorers?league=${l.api}&season=${season}`,{'x-apisports-key':apif});if(Object.keys(d.errors??{}).length)throw Error(playerError(d.errors));if(!Array.isArray(d.response))throw Error('Format joueurs indisponible.');return d.response});if(Array.isArray(r.data))for(const row of r.data){for(const st of row.statistics??[]){if(st.league?.id!==l.api||st.league?.season!==season)continue;const minutes=st.games?.minutes??null;players.push({id:`api:${row.player.id}:${st.team.id}:${season}`,name:row.player.name,team:st.team.name,league:l.id,season,appearances:st.games?.appearences??null,starts:st.games?.lineups??null,minutes,goals:st.goals?.total??null,assists:st.goals?.assists??null,shots:st.shots?.total??null,onTarget:st.shots?.on??null,penaltyGoals:st.penalty?.scored??null,goals90:minutes>=450&&st.goals?.total!=null?90*st.goals.total/minutes:null,assists90:minutes>=450&&st.goals?.assists!=null?90*st.goals.assists/minutes:null,xg:null,xa:null,recent:null,source:'API-Football',scope:'Top buteurs ; liste partielle de joueurs',collectedAt:r.collectedAt,stale:r.stale})}}}
 coverage.push({league:l.name,season,count:players.filter(p=>p.league===l.id).length,status:r?.error||(!apif?'Clé API-Football absente':rights!=='true'?'Droits de réutilisation API-Football à confirmer':'Aucun joueur fourni'),alternativeError:fdError||null});}
 return {players,coverage,season,historical:season!==Number(seasonFor(parisDate()).slice(0,4))};}
