import {oddsWindow} from './compact';
import {matchEvent,playerError} from './matching';
import {secret} from '@/lib/football/secrets';
import {boundedBudget} from './config';
import {LEAGUES,normalizeOpen,parisDate,seasonFor,type Match,type Quote} from './core';
import {cached,setting,reserve,database,readCache,lock} from './store';
import snapshots from '../../data/snapshots.json';
const seeds=snapshots as Record<string,any>;
async function jsonFetch(url:string,headers:Record<string,string>={}){let r:Response;try{r=await fetch(url,{headers,signal:AbortSignal.timeout(15000)});}catch{throw new Error('Fournisseur injoignable')}if(!r.ok)throw new Error(r.status===429?'Quota fournisseur épuisé':r.status===403||r.status===401?'Clé ou couverture refusée':`Fournisseur indisponible (${r.status})`);return {data:await r.json() as any,headers:r.headers}}
async function fdRequest(path:string){const day=new Date().toISOString().slice(0,10);if(!await reserve('fd:minute:'+new Date().toISOString().slice(0,16),1,8)||!await reserve('fd:day:'+day,1,boundedBudget(setting('CALENDAR_DAILY_BUDGET'),80,80)))throw new Error('Budget calendrier épuisé');return (await jsonFetch('https://api.football-data.org/v4/'+path,{'X-Auth-Token':(await secret('FOOTBALL_DATA_KEY'))})).data}
export async function loadLeague(league:typeof LEAGUES[number],season:string){
 const key=`openfootball:${season}:${league.id}`;let cache:any;
 try{cache=await cached(key,24*3600000,async()=>{if(!await reserve('open:'+new Date().toISOString().slice(0,10),1,boundedBudget(setting('OPEN_DAILY_BUDGET'),20,20)))throw new Error('Budget source ouverte épuisé');return (await jsonFetch(`https://raw.githubusercontent.com/openfootball/football.json/master/${season}/${league.id}.json`)).data})}catch{cache={data:null,collectedAt:null,stale:true,error:'Cache persistant indisponible'}}
 const seed=seeds[`${season}-${league.id}`];const raw=cache.data??seed?.payload,at=cache.data?cache.collectedAt:seed?.collectedAt;
 return {matches:raw?normalizeOpen(raw,league.id,season,at):[],coverage:{id:league.id,name:league.name,source:'OpenFootball',available:!!raw,collectedAt:at??null,stale:cache.stale||!cache.data,error:cache.error,season,sourceFreshness:'Actualisation amont non garantie ; heure non certifiée'}};
}
export async function loadMatches(day:string){const season=seasonFor(day);const open=await Promise.all(LEAGUES.map(l=>loadLeague(l,season)));let matches=open.flatMap(x=>x.matches);const coverage=open.map(x=>x.coverage);
 if((await secret('FOOTBALL_DATA_KEY'))){
 for(const l of LEAGUES){const r=await cached(`fd:${season}:${l.fd}`,6*3600000,()=>fdRequest(`competitions/${l.fd}/matches?season=${season.slice(0,4)}`));if(!Array.isArray(r.data?.matches))continue;
 const rows:Match[]=r.data.matches.map((m:any)=>({id:`fd:${m.id}`,league:l.id,season,date:parisDate(m.utcDate),utc:m.utcDate,home:m.homeTeam.name,away:m.awayTeam.name,homeAliases:[m.homeTeam.shortName].filter(Boolean),awayAliases:[m.awayTeam.shortName].filter(Boolean),homeId:`fd:${m.homeTeam.id}`,awayId:`fd:${m.awayTeam.id}`,hg:m.score?.duration==='REGULAR'?m.score?.fullTime?.home??null:m.score?.regularTime?.home??null,ag:m.score?.duration==='REGULAR'?m.score?.fullTime?.away??null:m.score?.regularTime?.away??null,status:m.status,source:'football-data.org',collectedAt:r.collectedAt!,round:m.matchday?`Journée ${m.matchday}`:null}));matches=matches.filter(m=>m.league!==l.id).concat(rows);coverage[LEAGUES.indexOf(l)]={...coverage[LEAGUES.indexOf(l)],source:'football-data.org',collectedAt:r.collectedAt,stale:r.stale,error:r.error,sourceFreshness:'Résultats différés, collecte toutes les 6 h'};}}
 return {matches,coverage};}
export async function collectOdds(force=false,matches?:Match[]){if(!(await secret('ODDS_API_KEY')))return {status:'Clé non configurée'};const results=[];for(const l of LEAGUES){if(matches&&!force){if(!oddsWindow(matches,l.id))continue;const last=await readCache(`odds:${l.id}`);if(last&&Date.now()-Date.parse(last.collected_at)<2*3600000)continue;if(!await lock('odds:auto:'+parisDate()+':'+l.id,86400000))continue;await database().prepare('UPDATE cache SET expires_at=0 WHERE key=?').bind(`odds:${l.id}`).run();}if(force)await database().prepare('UPDATE cache SET expires_at=0 WHERE key=?').bind(`odds:${l.id}`).run();const r=await cached(`odds:${l.id}`,24*3600000,async()=>{ // 5 sports × 2 markets × 1 region × 31 days = 310 credits.
 if(!await reserve('odds:rolling:'+new Date().toISOString().slice(0,7),2,boundedBudget(setting('ODDS_MONTHLY_BUDGET'),400,400)))throw new Error('Budget cotes épuisé');const state=await readCache('odds:provider-quota');if(state?.data?.remaining!==undefined&&state.data.remaining<52)throw new Error('Réserve fournisseur atteinte');
 const result=await jsonFetch(`https://api.the-odds-api.com/v4/sports/${l.odds}/odds/?apiKey=${encodeURIComponent((await secret('ODDS_API_KEY')))}&regions=eu&markets=h2h,totals&oddsFormat=decimal&dateFormat=iso`);
 const remaining=Number(result.headers.get('x-requests-remaining'));if(Number.isFinite(remaining))await database().prepare('INSERT INTO cache(key,payload,collected_at,expires_at) VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET payload=excluded.payload,collected_at=excluded.collected_at').bind('odds:provider-quota',JSON.stringify({remaining}),new Date().toISOString(),Date.now()+86400000).run();return result.data;});results.push({league:l.id,stale:r.stale,error:r.error})}return results}
export async function quotesFor(matches:Match[]):Promise<Quote[]>{const quotes:Quote[]=[];const mapped=(await database().prepare("SELECT key,internal_id FROM mappings WHERE key LIKE 'odds:event:%'").all()).results;const mappingById=new Map(mapped.map((r:any)=>[r.key,r.internal_id as string]));for(const l of LEAGUES){const r=await readCache(`odds:${l.id}`);if(!Array.isArray(r?.data))continue;for(const event of r.data){ // Explicit event ID mapping only. Never a name-only join.
 const internal=mappingById.get('odds:event:'+event.id);let mapping=internal?{internal_id:internal}:null;if(!mapping){const candidate=matchEvent(event,l.id,matches);if(candidate){const evidence=JSON.stringify({method:'unique-competition-kickoff-ordered-teams-v1',eventId:event.id,matchId:candidate.id,kickoff:event.commence_time,home:event.home_team,away:event.away_team,at:new Date().toISOString()});await database().prepare('INSERT INTO mappings(key,internal_id,evidence) VALUES(?,?,?) ON CONFLICT(key) DO NOTHING').bind('odds:event:'+event.id,candidate.id,evidence).run();mapping={internal_id:candidate.id};}}const match=matches.find(m=>m.id===mapping?.internal_id);if(!match||!match.utc||Math.abs(Date.parse(match.utc)-Date.parse(event.commence_time))>3600000)continue;
 for(const b of event.bookmakers??[])for(const market of b.markets??[])for(const o of market.outcomes??[]){if(!Number.isFinite(o.price)||o.price<=1)continue;const outcome=o.name===event.home_team?'home':o.name===event.away_team?'away':o.name==='Draw'?'draw':o.name;quotes.push({matchId:match.id,market:market.key,outcome,price:o.price,point:o.point,bookmaker:b.title,updatedAt:market.last_update??b.last_update,collectedAt:r.collected_at,source:'The Odds API'})}}}return quotes}
export async function collectPlayers(){if(!(await secret('API_FOOTBALL_KEY')))return {status:'Clé non configurée'};if((await secret('API_FOOTBALL_RIGHTS_CONFIRMED'))!=='true')return {status:'Droits de réutilisation à confirmer'};const season=Number((await secret('PLAYER_SEASON'))||seasonFor(parisDate()).slice(0,4));const results=[];for(const l of LEAGUES){const r=await cached(`players:${l.id}:${season}`,86400000,async()=>{const all=[];let page=1,total=1;do{if(!await reserve('apif:'+new Date().toISOString().slice(0,10),1,boundedBudget(setting('PLAYERS_DAILY_BUDGET'),80,80)))throw new Error('Budget joueurs épuisé ; pagination incomplète non publiée');const {data}=await jsonFetch(`https://v3.football.api-sports.io/players?league=${l.api}&season=${season}&page=${page}`,{'x-apisports-key':(await secret('API_FOOTBALL_KEY'))});if(Object.keys(data.errors??{}).length)throw new Error(playerError(data.errors));total=data.paging?.total??1;all.push(...data.response);page++;if(page>80&&page<=total)throw new Error('Pagination supérieure au budget');}while(page<=total);return all;});results.push({league:l.id,error:r.error})}return results}
export async function loadPlayers(){const season=Number((await secret('PLAYER_SEASON'))||seasonFor(parisDate()).slice(0,4));const list=[];for(const l of LEAGUES){const r=await readCache(`players:${l.id}:${season}`);if(!Array.isArray(r?.data))continue;for(const row of r.data){for(const st of row.statistics??[]){if(st.league?.id!==l.api||st.league?.season!==season)continue;const minutes=st.games?.minutes??null;list.push({id:`api:${row.player.id}:${st.team.id}:${season}`,name:row.player.name,team:st.team.name,league:l.id,season,appearances:st.games?.appearences??null,starts:st.games?.lineups??null,minutes,goals:st.goals?.total??null,assists:st.goals?.assists??null,shots:st.shots?.total??null,onTarget:st.shots?.on??null,penaltyGoals:st.penalty?.scored??null,goals90:minutes>=450&&st.goals?.total!=null?90*st.goals.total/minutes:null,assists90:minutes>=450&&st.goals?.assists!=null?90*st.goals.assists/minutes:null,xg:null,xa:null,recent:null,source:'API-Football',collectedAt:r.collected_at,stale:r.expires_at<Date.now()})}}}return list}
export async function unmatchedOdds(day:string){const list:any[]=[];for(const l of LEAGUES){const r=await readCache(`odds:${l.id}`);if(!Array.isArray(r?.data))continue;for(const e of r.data){if(parisDate(e.commence_time)!==day)continue;const mapping=await database().prepare('SELECT internal_id FROM mappings WHERE key=?').bind('odds:event:'+e.id).first();if(mapping)continue;const quotes=[];for(const b of e.bookmakers??[])for(const market of b.markets??[])for(const o of market.outcomes??[])if(market.key==='h2h'&&Number.isFinite(o.price)&&o.price>1)quotes.push({outcome:o.name,price:o.price,bookmaker:b.title,updatedAt:market.last_update??b.last_update});list.push({id:e.id,league:l.name,home:e.home_team,away:e.away_team,utc:e.commence_time,source:'The Odds API',quotes})}}return list}
