import {env} from 'cloudflare:workers';
export function database(){if(!env.DB)throw new Error('Base persistante indisponible');return env.DB}
export function setting(key:string){return (env as unknown as Record<string,string>)[key]||process.env[key]||''}
export async function readCache(key:string){const row=await database().prepare('SELECT * FROM cache WHERE key=?').bind(key).first<any>();return row?{...row,data:JSON.parse(row.payload)}:null}
export async function lock(key:string,ms=60000){const now=Date.now();const r=await database().prepare('INSERT INTO locks(key,until) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET until=excluded.until WHERE locks.until < ? RETURNING key').bind(key,now+ms,now).first();return !!r}
export async function reserve(key:string,cost:number,limit:number){if(cost<1||!Number.isInteger(cost))throw new Error('Coût invalide');const r=await database().prepare('INSERT INTO budget(key,used,"limit") SELECT ?,?,? WHERE ?<=? ON CONFLICT(key) DO UPDATE SET used=budget.used+excluded.used,"limit"=excluded."limit" WHERE budget.used+excluded.used<=excluded."limit" RETURNING used').bind(key,cost,limit,cost,limit).first();return !!r}
export async function cached(key:string,ttl:number,fetcher:()=>Promise<any>){const old=await readCache(key);if(old&&old.expires_at>Date.now())return {data:old.data,collectedAt:old.collected_at,stale:!!old.error,error:old.error??null};if(!await lock(key))return {data:old?.data??null,collectedAt:old?.collected_at??null,stale:true,error:'Collecte en cours'};
 try{const data=await fetcher();const at=new Date().toISOString();await database().batch([database().prepare('INSERT INTO cache(key,payload,collected_at,expires_at,error) VALUES(?,?,?,?,NULL) ON CONFLICT(key) DO UPDATE SET payload=excluded.payload,collected_at=excluded.collected_at,expires_at=excluded.expires_at,error=NULL').bind(key,JSON.stringify(data),at,Date.now()+ttl),database().prepare('INSERT INTO observations(entity_id,kind,source,collected_at,reference,payload) VALUES(?,?,?,?,?,?)').bind(key,'provider-response',key.split(':')[0],at,key,JSON.stringify(data))]);return {data,collectedAt:at,stale:false,error:null};}
 catch(e){const message=e instanceof Error?e.message:'Source indisponible';await database().prepare('INSERT INTO cache(key,payload,collected_at,expires_at,error) VALUES(?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET error=excluded.error,expires_at=excluded.expires_at').bind(key,JSON.stringify(old?.data??null),old?.collected_at??new Date().toISOString(),Date.now()+15*60000,message).run();return {data:old?.data??null,collectedAt:old?.collected_at??null,stale:true,error:message};}}
